services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod-app
    restart: always
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/roors
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: 462a47d02e9a48590f50df088282c3ad
      JWT_EXPIRATION: 3600000
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - prod-network

  db:
    image: postgres:17
    container_name: prod-postgres
    restart: always
    environment:
      POSTGRES_DB: roors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - prod-network

volumes:
  postgres-data:

networks:
  prod-network:
    driver: bridge